version: "3.9"

services:
  api_csv:
    build: .
    container_name: meli_api_csv
    environment:
      - STORAGE=csv
      - CSV_PATH=names_dataset.csv
      - CACHE_MAX=256
      - NGRAM_N=3
      - MAX_CANDIDATES=2000
    ports:
      - "8000:8000"
    
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health').read()\""]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  api_sqlite:
    build: .
    container_name: meli_api_sqlite
    environment:
      - STORAGE=sqlite
      - CSV_PATH=names_dataset.csv
      - SQLITE_PATH=/data/names.db
      - SQLITE_FORCE_RELOAD=false
      - CACHE_MAX=256
      - NGRAM_N=3
      - MAX_CANDIDATES=2000
    volumes:
      - sqlite_data:/data
    ports:
      - "8001:8000"

    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health').read()\""]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

volumes:
  sqlite_data:
